---
- name: OS initial Setting
  hosts: role_firstmallserver
  user: rocky
  become: true
  become_method: sudo




  roles:
    - role: "../roles/os_setting"
    - role: "../roles/app/apache24_phpfpm82"
    - role: "../roles/app/mysql80"
