- name: HASP 디렉터리 생성
  file: 
    path: /usr/local/hasp
    state: directory
    mode: '0755'

- name: HASP 파일 rsync
  shell: | 
    rsync -a {{ SETUP }}::set/config/hasp/ /usr/local/hasp/

- name: pipenv 설치
  pip:
    name: pipenv==2022.4.8
    executable: pip3

- name: pipenv 가상환경 생성 및 패키지 설치
  shell: |
    export PIPENV_VENV_IN_PROJECT=true
    pipenv --python python3
    pipenv install 
  args:
    chdir: /usr/local/hasp
  environment:
    PIPENV_VENV_IN_PROJECT: "true"


- name: HASP 시작
  shell: |
    ./haspd start
  args:
    chdir: /usr/local/hasp 
