- name: 4-1. disabled 서비스
  systemd:
    name: "{{ item }}"
    state: stopped 
    enabled: no 
  loop: "{{ disabled_services }}"
  ignore_errors: yes


- name: 4-2. enabled 서비스
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ enabled_services }}"
  ignore_errors: yes


