name: "생성된 EC2 인스턴스에 (Role: firstmallserver) 플레이북 배포"

on:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: self-hosted

    steps:
    - name: "1. 앤서블 코드 다운로드"
      uses: actions/checkout@v4

    - name: "2. AWS API 조회를 위한 프로파일 키 값 전달"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GEON }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEON }}
        aws-region: ap-northeast-2

    - name: "3. 플레이북 문법검사"
      run: |
        ansible-playbook -i inventory/aws_ec2.yml playbook/first_setting.yml --syntax-check

    - name: "4. 플레이북 배포"
      run: |
        ansible-playbook -i inventory/aws_ec2.yml playbook/first_setting.yml
