name: "생성된 EC2 인스턴스에 (Role: webserver) 플레이북 배포"

on:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: self-hosted

    steps:
    - name: "1. 앤서블 코드 다운로드"
      uses: actions/checkout@v4

    - name: "2. AWS API 조회를 위한 프로파일 키 값 전달"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STEPHANE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STEPHANE }}
        aws-region: ap-northeast-2

    - name: "3. 플레이북 배포 (배스천 호스트를 프록시로 경유)"
      run: |
        BASTION_PRIVATE_IP=$(ansible-inventory -i inventory/aws_ec2.yml --graph | grep -A 1 role_bastionhost | tail -n 1 | tr -d ' |`-')
        BASTION_IP=$(ansible-inventory -i inventory/aws_ec2.yml --host $BASTION_PRIVATE_IP | jq -r '.public_ip_address')

        echo "배스천 호스트 공인 ip: $BASTION_IP"

        ansible-playbook -i inventory/aws_ec2.yml playbook/first_setting/os_app_install.yml --vault-password-file=decrypt.txt -e "ansible_ssh_common_args='-o ProxyJump=rocky@${BASTION_IP} -o StrictHostKeyChecking=no'" -vvv
